variable "environment" {}
variable "amis" {}
variable "aws_region" {}
variable instance_type {}
variable "key_name" {}
variable "public-subnets" {}
variable "private-subnets" {}
variable "sg_id" {}
variable "vpc_name" {}
#variable elb_listener {} 
variable elb_listener_public {}
variable iam_instance_profile {}
